---
format:
  pdf:
    number-sections: false

bibliography: memo.bib
tables: true # enable longtable and booktabs
fontsize: 12pt
indent: true
geometry: margin=1in
linestretch: 1.5 # double spacing using linestretch 1.5
colorlinks: true

execute:
  echo: false
  message: false
  warning: false
  dpi: 300
    
title:  Macrointerest Across Countries
subtitle: Memo to Editor and Reviewers
---

```{=tex}
\setcounter{figure}{0}
\renewcommand*{\thefigure}{M\arabic{figure}}
```

## Introduction {.unnumbered}
**Framing**.
We appreciate the reviewers' careful reading and their suggestions for better framing the piece.
Following Reviewer 1's suggestion, we reorganized the introduction into three paragraphs.
The first addresses the relevance of macrointerest.
Reviewer 2 asked us to provide more theoretical discussion on macrointerest, and minding the editor's instruction to limit this to "a bit more," we did so here. 
The second paragraph reviews the challenges faced by previous research.
R1 specifically suggested that we contrast our work with that of @Peterson2022, and we added that to this second paragraph.
(Also at R1's suggestion, we included an appendix comparing our estimates of macrointerest for the United States with those presented in that article; see Appendix E.)
The third paragraph previews our specific contribution and findings.
We agree that the original introduction was too brisk, and we see this as a substantial improvement.

One point that both reviewers flagged was the "good times versus bad" framing of the hypotheses regarding the circumstances that prompt higher levels of macrointerest, pointing out that this wording does not correspond very well to the paper's findings.
Here in the introduction and throughout, we adopted the more accurate "good economic conditions" phrase to better reflect the higher mean levels and positive change in GDP per capita plus lower mean levels of income inequality that we found to be associated with higher macrointerest in our analysis.

**Replication Materials**
R2 longed to see our replication materials during the review process.
We, as reviewers, have often made similar wishes.
We are told by the _BJPS_ editor that making those materials available to reviewers is not presently possible.
In the final version, we will of course provide full replication materials on the Dataverse as well as the link to the Github repository with the paper's complete revision history.


## Cross-National Macrointerest: The Source Data {.unnumbered}
**`DCPOtools`**.
On the recommendation of R1, we expanded and moved our discussion of the automation of the data cleaning process to Appendix A.


## Estimating Cross-National Macrointerest {.unnumbered}
**Method Comparison**. 
R1 suggested that we bring our discussion of the merits of the DCPO approach relative to alternatives from a footnote to the text.
We have adopted this suggestion at page 4.


## Validating Cross-National Macrointerest {.unnumbered}
**Validation**.
R2 raised questions about "the validation exercise," pointing to a lack of benchmarks for the "evaluations of the size of the correlation coefficients."
While any benchmark regarding correlations is bound to be somewhat arbitrary, the correlations for the similar internal convergent validation tests in @Caughey2019 [, 686, Figure 6, columns 1 and 3], which we cited in this regard (now at page 5), range in absolute value from .73 to .92.
The range of correlations we report on page 8, from .71 to .88, seem to us to be similarly satisfying.

We also investigated the reviewer's speculation that items with more observations would yield higher correlations with the macrointerest estimates and for "small projects with few surveys" the correlation would be smaller in a way that would call into question the utility of the method.
First, we calculated the mean response for each item in each country-year observed.
(This is not quite the same procedure as we use in our validation exercises; there, we dichotomize the items and take the percentage of respondents giving higher responses, but while that route yields nicer plots, this one was easier to scale across dozens of items.)

Then, we calculated the correlation for each item across country-years between these mean responses and the macrointerest estimates.
This correlation was .9 or higher for twenty-seven of our fifty-three items. It was below .7 for just two.
Finally, we observed the relationship between items' correlations and their number of observations.
This relationship is nearly nonexistent, as shown in Figure M1 below, and is in the direction contrary to R2's speculative hypothesis.

```{r itcor, fig.align='center', fig.cap="Relationship Between Items' Correlations with Macrointerest and Their Number of Observations"}
library(tidyverse)
library(DCPOtools)

dcpo_input_raw <- read_csv(here::here("data", "dcpo_input_raw.csv"),
                           col_types = "cdcddcd")

load(here::here("data",
                "theta_summary.rda"))

process_dcpo_input_raw <- function(dcpo_input_raw_df) {
  dcpo_input_raw_df %>% 
    mutate(item = if_else(item == "int5_polit" &
                            year < 1990,
                          "int3_polit",
                          item),
           r = if_else(item == "int5_polit" &
                         year < 1990,
                       r - 2,
                       r)) %>% 
    filter(year >= 1982 & n > 0) %>% 
    with_min_yrs(3) %>% 
    with_min_cy(5) %>% 
    with_min_yrs(3) %>%
    group_by(country) %>% 
    mutate(cc_rank = n()) %>% 
    ungroup() %>% 
    arrange(-cc_rank)
}

dcpo_input_raw1 <- dcpo_input_raw %>% 
  process_dcpo_input_raw()

item_theta_cor <- dcpo_input_raw1 %>% 
  group_by(item) %>% 
  mutate(n_item = sum(r==1)) %>% 
  ungroup() %>% 
  group_by(country, year, item) %>% 
  summarize(mean_item = sum(r*n)/sum(n),
            se_item = sqrt(sum((r*n - mean_item*n)^2)/{sum(n) - 1})/sqrt(sum(n)),
            n_item = first(n_item),
            cc_rank = first(cc_rank)) %>% 
  left_join(theta_summary %>% select(country, year, theta = mean),
            by = c("country", "year")) %>% 
  ungroup() %>% 
  group_by(item) %>% 
  summarize(theta_cor = cor(theta, mean_item),
            n_item = first(n_item))

itcor <- with(item_theta_cor, cor(theta_cor, n_item)) %>% 
  sprintf("%.2f", .) %>% 
  paste("R =", .)

item_theta_cor %>% 
  ggplot(aes(x = n_item, y = theta_cor)) +
  geom_point() +    # Use hollow circles
  geom_smooth(method="loess") +  # Add linear regression line 
  ylim(c(0, 1)) +
  labs(x = "Item Number of Country-Year Observations",
    y = "Correlation Between Item Country-Year Means\nand Macrointerest Estimates") +
  annotate(geom = "text", 
           x = 265,
           y = 1,
           label = itcor)
```


## Testing Theories of Macrointerest Cross-Nationally {.unnumbered}
**Comparison to the ESS**
R2 asked why we would analyze macrointerest in only the advanced democracies of the OECD when we could simply use the ESS data "and save ourselves all the harmonization effort?"
This point is two-pronged.
To address its first part, we examine the advanced democracies because that is where the extant theories of macrointerest apply.
To our knowledge, political scientists have as yet had relatively little to say regarding, for example, explanations for the public's interest in politics in authoritarian countries.
We now emphasize that we restrict our sample for theoretical reasons at page 7.

The question of the payoff of our estimates is easily answered, even within this sample of relatively data-rich countries.
Our macrointerest estimates, by drawing on all of the available survey data on political interest, provide _many_ more country-years to work with than the ESS (which is, as R2 implied, the best alternative).
The ESS includes only 17.3% of the country-year observations that our macrointerest data make available.
We review this key advantage in Appendix C.


**Two-Step Approach**
R1 raised the question whether the analysis "could be achieved in a single step by integrating hierarchical priors into the model."
We were somewhat puzzled by this comment, but we guessed the reviewer was referring to combining the measurement and analysis steps into a single model, as in @Claassen2022.
We prefer to avoid such an approach, because it assumes that the indicators of macrointerest are missing at random with regard to the independent variables, and therefore that the relationship between macrointerest and these variables is the same in the countries when and where macrointerest is poorly observed as in the country-years where macrointerest is well observed, and this assumption is difficult to justify.
If the reviewer had a different "single step" approach in mind, we apologize for not figuring it out.

**Uncertainty**. 
In response to R1's suggestion to provide more details about how we incorporated uncertainty in our analysis, we made a specific discussion at page 11. 
We used the "Method of Composition" to account for the uncertainty in the ex post analysis based on the estimated latent variable together with others. 
This is a method that has been used in a series of latent variable analyses in political science. 
We listed several other applications and also direct readers to a more detailed technical note of how the method is incorporated in the DCPO framework.


## Conclusions
**Participation**.
R2 provides an intriguing insight for the theoretical implication of the theory test section of our research that the findings suggest the distinctiveness of macrointerest with other types of participation/engagements. 
Although there is little room for a more sufficient discussion due to the word limit, we pointed out this insight to the readers and direct them to relative literature for further comparison.


## Appendices

### Survey Items Used to Estimate Macrointerest
**Full Survey References**
R2 asked for additional information in Appendix A on the source data,
requesting "references to all survey datasets used in the analysis."  We now provide citations to all of the surveys in Table A2. As the reviewer anticipated, this did indeed "take many pages," but we agree that it is a valuable addition.

**Legibility of Figure A1**
R2 also pointed out that Figure A1 was hard to read and suggested splitting it. 
We split that figure into several panels by region to allow it to be split across pages and so expanded for better legibility. 

**Included projects**
R2 queried if "single-country and single-wave projects should be included."
All of the survey items we employ include at least five country-years of data (a point we now make explicit at page 2).
This means that single-wave projects include at least five countries, as exemplified in these data by the survey "Values and Political Change in Post-Communist Europe, 1993-1994."
Even such small cross-national surveys contain at least some information regarding the differences across countries.
The cost is that country-specific item bias cannot be estimated and so is set to zero, potentially resulting in additional measurement error [see @Solt2020c, 6].
It also means that single-country projects incorporate at least five years (in fact, the minimum in this dataset is seven, in both the Canadian National Election Studies and the Korea Barometer).
This provides considerable information about changes over time within those countries, and country-specific item bias is of course not an issue for data drawn from only a single country.


### The DCPO Model
**Source data sample representation**.
We thank R2 for pointing out the matter of sample representation.
We have added a paragraph here discussing the issue here.
The short of it is that unlike the model employed by @Caughey2019, the DCPO model does not incorporate a poststratification component to correct for this problem, and the result is greater measurement uncertainty in the estimates where data is relatively rich and potential bias in the estimates where data is more sparse.


**Scaling of estimates**. 
R1 suggested that we consider employing the cumulative distribution function (CDF) of the normal distribution---that is, the probit transformation---as an alternative to the logistic transformation, for scaling responses on the unit interval within the DCPO framework or at least discuss the relative merits of the two in the appendix.
We appreciate the suggestion of the probit transformation.
The preference for the logistic function in the DCPO model is grounded in its inherent flexibility and enhanced tolerance for deviations from standard normal assumptions. 
Pertinently, within the macrointerest context, we see little reason to presume that the the source data are devoid of extreme values or adhere to a symmetric distribution. 
The logistic transformation exhibits greater leniency under such conditions compared to the normal CDF. 
On the other hand, we concur with R1 that the interpretation of the probit transformation is more intuitive.
We have added a discussion of these points to Appendix B, our summary of the DCPO model.
And as the DCPO model is published as open source software on CRAN [@Solt2020a], future researchers have the option of modifying the transformation method if they see fit. 

### Macrointerest Scores Over Time
R2 pointed out that the "appendix should show the trajectories for all countries."
We have added those plots here as Appendix D. 


# Reference {-}

